package com.cms.service.impl;

import com.cms.model.dto.ContactDTO;
import com.cms.model.entity.Contact;
import com.cms.model.entity.ContactEmail;
import com.cms.model.entity.ContactPhone;
import com.cms.model.entity.User;
import com.cms.repository.ContactRepository;
import com.cms.repository.UserRepository;
import com.cms.service.ContactService;
import com.cms.util.ContactMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * ContactServiceImpl is the actual implementation of the ContactService interface.
 *
 * This class contains all the real business logic for managing contacts:
 * creating, reading, updating, deleting, and searching.
 *
 * @Service  → tells Spring this is a service bean (Spring manages its lifecycle)
 * @RequiredArgsConstructor → Lombok auto-generates a constructor that injects all
 *                            final fields (contactRepository, userRepository, contactMapper)
 * @Slf4j    → Lombok adds a `log` object so we can write log messages easily
 * @Transactional → wraps each method in a database transaction, so if anything
 *                  goes wrong mid-method the database is automatically rolled back
 */
@Service
@RequiredArgsConstructor
@Slf4j
@Transactional
public class ContactServiceImpl implements ContactService {

    // Spring automatically injects these three dependencies via the constructor
    // (generated by @RequiredArgsConstructor) — no need to write @Autowired.
    private final ContactRepository contactRepository;
    private final UserRepository userRepository;
    private final ContactMapper contactMapper;

    // =========================================================================
    // CREATE CONTACT
    // =========================================================================

    /**
     * Creates a new contact and saves it to the database, linked to the
     * currently logged-in user.
     */
    @Override
    public ContactDTO createContact(ContactDTO dto, String userEmail) {

        // Step 1: Look up the User in the database using their email address.
        // If no user is found, throw an exception — we can't create a contact
        // without a valid owner.
        User user = userRepository.findByEmail(userEmail)
                .orElseThrow(() -> new RuntimeException("User not found: " + userEmail));

        // Step 2: Convert the incoming ContactDTO into a Contact entity
        // (the format the database understands) using our mapper utility.
        // The mapper also links the contact to the user and sets createdAt.
        Contact contact = contactMapper.toEntity(dto, user);

        // Step 3: Save the Contact entity to the database.
        // Because CascadeType.ALL is set on emails and phones, this single save
        // also saves all the associated emails and phone numbers automatically.
        Contact savedContact = contactRepository.save(contact);

        // Step 4: Log a confirmation message so we can trace this in server logs.
        log.info("Contact created for user: {}", userEmail);

        // Step 5: Convert the saved entity back to a DTO and return it.
        // The returned DTO will now include the auto-generated database ID.
        return contactMapper.toDTO(savedContact);
    }

    // =========================================================================
    // UPDATE CONTACT
    // =========================================================================

    /**
     * Updates an existing contact's fields. Only the owner of the contact
     * is allowed to update it.
     */
    @Override
    public ContactDTO updateContact(Long id, ContactDTO dto, String userEmail) {

        // Step 1: Find the contact in the database by its ID.
        // If no contact exists with that ID, throw an exception.
        Contact contact = contactRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Contact not found with id: " + id));

        // Step 2: Verify that the logged-in user actually owns this contact.
        // If the contact belongs to someone else, deny access immediately.
        if (!contact.getUser().getEmail().equals(userEmail)) {
            throw new RuntimeException("Access denied: you do not own this contact");
        }

        // Step 3: Update all the simple (non-list) fields on the existing entity.
        // We don't create a new Contact — we update the one already in the database.
        contact.setFirstName(dto.getFirstName());
        contact.setLastName(dto.getLastName());
        contact.setTitle(dto.getTitle());
        contact.setCompany(dto.getCompany());
        contact.setAddress(dto.getAddress());
        contact.setNotes(dto.getNotes());

        // Step 4: Replace the existing emails list with the new one from the DTO.
        // We clear the old list first (which triggers orphanRemoval to delete old rows),
        // then map and add the new EmailDTOs as ContactEmail entities.
        contact.getEmails().clear();
        if (dto.getEmails() != null) {
            List<ContactEmail> updatedEmails = new ArrayList<>();
            for (ContactDTO.EmailDTO emailDTO : dto.getEmails()) {
                ContactEmail contactEmail = ContactEmail.builder()
                        .email(emailDTO.getEmail())
                        .label(emailDTO.getLabel())
                        .isPrimary(emailDTO.isPrimary())
                        .contact(contact)   // link back to the parent contact
                        .build();
                updatedEmails.add(contactEmail);
            }
            contact.getEmails().addAll(updatedEmails);
        }

        // Step 5: Replace the existing phones list with the new one from the DTO.
        // Same clear-then-add pattern as emails above.
        contact.getPhones().clear();
        if (dto.getPhones() != null) {
            List<ContactPhone> updatedPhones = new ArrayList<>();
            for (ContactDTO.PhoneDTO phoneDTO : dto.getPhones()) {
                ContactPhone contactPhone = ContactPhone.builder()
                        .phone(phoneDTO.getPhone())
                        .label(phoneDTO.getLabel())
                        .isPrimary(phoneDTO.isPrimary())
                        .contact(contact)   // link back to the parent contact
                        .build();
                updatedPhones.add(contactPhone);
            }
            contact.getPhones().addAll(updatedPhones);
        }

        // Step 6: Record the time this update happened.
        // The @PreUpdate hook in the Contact entity also does this automatically,
        // but we set it explicitly here as well for clarity.
        contact.setUpdatedAt(LocalDateTime.now());

        // Step 7: Save the updated contact to the database and convert it to a DTO.
        Contact savedContact = contactRepository.save(contact);
        return contactMapper.toDTO(savedContact);
    }

    // =========================================================================
    // DELETE CONTACT
    // =========================================================================

    /**
     * Permanently deletes a contact from the database.
     * Only the owner of the contact can delete it.
     */
    @Override
    public void deleteContact(Long id, String userEmail) {

        // Step 1: Find the contact in the database by its ID.
        // Throw an exception if it doesn't exist.
        Contact contact = contactRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Contact not found with id: " + id));

        // Step 2: Check that the logged-in user owns this contact.
        // If not, deny access — users must not be able to delete each other's contacts.
        if (!contact.getUser().getEmail().equals(userEmail)) {
            throw new RuntimeException("Access denied: you do not own this contact");
        }

        // Step 3: Delete the contact from the database.
        // Because of CascadeType.ALL + orphanRemoval, all associated emails and
        // phones are automatically deleted along with the contact.
        contactRepository.delete(contact);

        // Step 4: Log the deletion event for auditing purposes.
        log.info("Contact deleted: {} by user: {}", id, userEmail);
    }

    // =========================================================================
    // GET CONTACT BY ID
    // =========================================================================

    /**
     * Fetches a single contact by its database ID.
     * Only the owner of the contact can view it.
     *
     * Note: @Transactional(readOnly = true) would be ideal here for performance,
     * but we inherit the class-level @Transactional for simplicity.
     */
    @Override
    public ContactDTO getContactById(Long id, String userEmail) {

        // Step 1: Find the contact in the database by its ID.
        // Throw an exception if it doesn't exist.
        Contact contact = contactRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Contact not found with id: " + id));

        // Step 2: Verify that the logged-in user owns this contact.
        // Prevents one user from reading another user's contacts.
        if (!contact.getUser().getEmail().equals(userEmail)) {
            throw new RuntimeException("Access denied: you do not own this contact");
        }

        // Step 3: Convert the entity to a DTO and return it.
        return contactMapper.toDTO(contact);
    }

    // =========================================================================
    // GET ALL CONTACTS (paginated)
    // =========================================================================

    /**
     * Returns a paginated, alphabetically sorted list of all contacts
     * belonging to the logged-in user.
     *
     * Pagination means instead of returning thousands of contacts at once,
     * we return them in "pages" (e.g. 20 at a time) for better performance.
     */
    @Override
    public Page<ContactDTO> getAllContacts(String userEmail, int page, int size) {

        // Step 1: Find the user in the database by email.
        // We need their ID to query only their contacts.
        User user = userRepository.findByEmail(userEmail)
                .orElseThrow(() -> new RuntimeException("User not found: " + userEmail));

        // Step 2: Create a Pageable object that tells Spring Data:
        // - which page number to fetch (0 = first page)
        // - how many items per page
        // - sort the results by firstName in A→Z order
        Pageable pageable = PageRequest.of(page, size, Sort.by("firstName").ascending());

        // Step 3: Fetch a page of Contact entities from the database
        // that belong to this specific user.
        Page<Contact> contacts = contactRepository.findByUserId(user.getId(), pageable);

        // Step 4: Convert each Contact entity in the page to a ContactDTO.
        // .map() works like a for-loop: it applies the mapper to every item in the page.
        return contacts.map(contactMapper::toDTO);
    }

    // =========================================================================
    // SEARCH CONTACTS (paginated)
    // =========================================================================

    /**
     * Searches the logged-in user's contacts by a keyword.
     * Matches against first name and last name (case-insensitive).
     * Returns results as a paginated list.
     */
    @Override
    public Page<ContactDTO> searchContacts(String userEmail, String keyword, int page, int size) {

        // Step 1: Find the user in the database by email so we have their ID.
        User user = userRepository.findByEmail(userEmail)
                .orElseThrow(() -> new RuntimeException("User not found: " + userEmail));

        // Step 2: Create a Pageable object for pagination.
        // No sorting specified here — results come back in database default order.
        Pageable pageable = PageRequest.of(page, size);

        // Step 3: Run the custom search query defined in ContactRepository.
        // It searches first name and last name for the keyword using LIKE,
        // scoped to only this user's contacts.
        Page<Contact> results = contactRepository.searchContactsByKeyword(
                user.getId(), keyword, pageable);

        // Step 4: Convert each matching Contact entity to a ContactDTO and return the page.
        return results.map(contactMapper::toDTO);
    }
}
